### ISSUE TITLE
Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by asedsami** [logux/server#117]
in this code
```
server.type('LOAD_NEXT_CANDLE', {
	async access(ctx) { return true },
	async resend(ctx) {
		console.log('resent')
		return 'candles-channel'
	},
	async process() {
		let candle = await CandleModel.findOne()

		server.log.add({ type: 'candles/new', candle }, { channels: ['candles-channel'] })
	}
})
```
when 'LOAD_NEXT_CANDLE' is dispatched on the client and the `process` is called on the server, I get this error:
```
 FATAL  Maximum call stack size exceeded at 2021-06-22 02:51:36
        at String.replace (<anonymous>)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:230:23)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
        at cleanFromKeys (file:///path/to/project/node_modules/@logux/server/create-reporter/index.js:232:21)
```
If I comment out the line that is making a call to the Database and send a fake candle, there's no error
```
server.type('LOAD_NEXT_CANDLE', {
	async access(ctx) { return true },
	async resend(ctx) {
		console.log('resent')
		return 'candles-channel'

	},
	async process() {
		// let candle = await CandleModel.findOne()
		let candle = {
			"_id": "60d0fae173565825312222ca",
			"pair": "eurusd",
			"timeframe": "1h",
			"date": "2000.01.03",
			"time": "19:00",
			"o": 1.0205,
			"h": 1.024,
			"l": 1.015,
			"c": 1.025,
			"v": 355,
		}
		server.log.add({ type: 'candles/new', candle }, { channels: ['candles-channel'] })
	}
})
```
If I do make a query to the database but still send the fake candle to the client, there's no error:
```
server.type('LOAD_NEXT_CANDLE', {
	async access(ctx) { return true },
	async resend(ctx) {
		console.log('resent')
		return 'candles-channel'

	},
	async process() {
		let dbCandle = await CandleModel.findOne()
		let candle = {
			"_id": "60d0fae173565825312222ca",
			"pair": "eurusd",
			"timeframe": "1h",
			"date": "2000.01.03",
			"time": "19:00",
			"o": 1.0205,
			"h": 1.024,
			"l": 1.015,
			"c": 1.025,
			"v": 355,
		}
		server.log.add({ type: 'candles/new', candle }, { channels: ['candles-channel'] })
	}
})
```

how do I fix this?

**Comment by ai** [comment]
Hm. I will try to look later today.

**Comment by ai** [comment]
Seems like you have circular dependency in `candle` from database.

Can you show `console.log(candle)` output in database’s version of the code?

**Comment by asedsami** [comment]
`console.log(candle)` logs:
```
{
  _id: 60d0fae173565825312222b8,
  numericId: 0,
  pair: 'eurusd',
  timeframe: '1h',
  date: '2000.01.03',
  time: '00:00',
  o: 1.0073,
  h: 1.0132,
  l: 1.0073,
  c: 1.0128,
  v: 194,
  isUpward: true,
  bh: 1.0128,
  bl: 1.0073,
  __v: 0
}
```

**Comment by ai** [comment]
Hm. Maybe it has some hidden key with `Symbol`?

Can you try:

```js
server.log.add({ type: 'candles/new', candle: JSON.parse(JSON.stringify(candle)) }, { channels: ['candles-channel'] })

**Comment by asedsami** [comment]
I'm not but that seems to be the case. it's working now! thank you.

**Comment by ai** [comment]
I added a better warning for cases like this

84c0aff

**Comment by asedsami** [comment]
I wanted to add a better warning but I didn't feel competent enough because I'm unfamiliar with the code.
