### ISSUE TITLE
`A timeout was reached` error

### ISSUE THREAD

**Issue by megatolya** [logux/server#122]
In my team's project we get many 'timeout was reached' errors from logux. We suppose it happens when the server restarts.

This timeout is managed in the Logux BaseNode: https://github.com/logux/core/blob/main/base-node/index.js#L247

...and it is started when another node connects to the server, see Logux ServerNode here: https://github.com/logux/core/blob/main/server-node/index.js#L26

I'm not sure how to investigate such error. And what exact nature of it. If you have any suggestions or recommendations on that, that would be very helpful.

![image](https://user-images.githubusercontent.com/2204267/151825422-fb85774a-2ad0-44e5-abb1-08427bfabdcd.png)

**Comment by ai** [comment]
Web Socket can’t be lost at any moment because of network error. There is no way to detect a broken WS connection without trying to send something over this WS. To be sure that WS is alive, every 10 second, client send `ping`. 

There are two common reasons why `A timeout was reached` could happen:

1. Client lost Internet connection. Server didn’t receive `ping` and drop broken WS connection.
2. Node.js process of Logux Server (or JS code of Logux client) is doing a non-stop job to long and had no time to write `ping` or `pong` to connection.

Seems like you have a second one. Start to detect it is server’s timeout or client’s timeout (they have a different error type). Then try to check available resources (for instance, Node.js has metric about event loop queue).

**Comment by megatolya** [comment]
It is node.js error:
```
instrument.ts:129 Error on Logux server:
 LoguxError: A timeout was reached (20000 ms)
    at FilteredNode.syncError (file:///home/node/uify_app/node_modules/@logux/core/base-node/index.js:225:15)
    at Timeout.<anonymous> (file:///home/node/uify_app/node_modules/@logux/core/base-node/index.js:253:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

It seems if tab with app stays unfocused for sometime this error occurs. It is either WS related issue or setTimeout is delayed thus node.js doesnt receive the message. 
And as you said
>To be sure that WS is alive, every 10 second, client send ping.

It seems quite possible that it is just because of the timeout delay then. The only concern is that I can't reproduce the same problem locally. Only with remote stand. But probably on localhost browser behaves differently and also development mode of logux might be different at some point. But that is just my thoughts
